ngx-translate/core

ng2-translate.ts
package.json
src/translate.service.ts

With this, users will be able to use the latest `angular cli`, which now has a new option:
`ng install ng2-translate` to auto-annotate their source if they choose, or custom install the lib.
https://github.com/angular/angular-cli/commit/019514681d990a54acfa6e1f46f7b6001a7674a8
@jkuri If you could also help @ocombe with the ability to target builds for `systemjs` and `webpack` in regards to how your implementation for `angular cli` expects would be great.

feat(cli): compatible with angular cli using 'ng install'

---

README.md

The README.md has a conflicting issue with path prefix, L#64 `var prefix = 'assets/i18n/'`
Since here we have slash again, between the two variables. This leads to // double slash problems in the URL. ```return this.http.get(`${this.sfLoaderParams.prefix}/${lang}${this.sfLoaderParams.suffix}`)``` 
[https://github.com/ocombe/ng2-translate/blob/master/src/translate.service.ts#L44](https://github.com/ocombe/ng2-translate/blob/master/src/translate.service.ts#L44)

Updated README.md to reflect correct path for prefix

---

README.md

- Update Readme to remove [deprecated @App usage](https://github.com/driftyco/ionic/blob/2.0/CHANGELOG.md#200-beta8-2016-06-06)

Remove deprecated @App decorator

---

src/translate.parser.ts

when the keys are shifted, somewhen the target gets set to undefined (L39). the loop terminates only after the next interation. in the meanwhile an exception is thrown and the further translation is aborted -> therefore added a check for undefined to exit the loop correctly without exception

[Issue#87] fix target undefined for missing translation

---

ng2-translate.ts

I haven't tested it with this module but in other cases this change fixed the problem.
Should close https://github.com/ocombe/ng2-translate/issues/218

fix(TranslateModule): use exported factory function to enable AOT compiling

---

src/translate.service.ts

Right now the current method does not support the various browsers well based on the users defaults. This change will work across IE10+, safari, chrome, and firefox

Update cross browser support for getBrowserLang

---

README.md
config/webpack.test.js
make.js
ng2-translate.ts
package.json
tsconfig.json

- uses `ngc` to generate the distribution files, making this compatible with AoT compilation. 
- distributes ES modules + UMD bundle, making this compatible with rollup/webpack2/treeshaking.
closes #218 
closes #248

chore(refactor): use ngc to compile for distro

---

README.md

The plugin is no longer needed since the feature it provided is now available in core. Just updates the note to point to a comment providing help on how to set it up.

docs: update on how to use with NativeScript

---

README.md
src/translate.service.ts
tests/translate.service.spec.ts

- pass `key`, `translateService`, and `interpolateParams` (if provided) to the `handle` method of `MissingTranslationHandler` for advanced  scenarios.
- `MissingTranslationHandler` README adjustments based on new function interface
Obsoletes #214, #230.
Closes #160, #221.

feat(MissingTranslationHandler): pass additional paramaters to `handle`

---

src/translate.service.ts

There's a bug in RxJS that breaks hot observables if one subscriber ignores errors (see https://github.com/ReactiveX/rxjs/issues/2145 ), which is causing #308. This patch fixes it by always handling observable errors (handling errors is a good idea anyway).
Fixes #308

Always handle observable errors

---

examples/webpack/package.json
examples/webpack/webpack.config.js

pull request for "ng2-translate with webpack does not work without copy-webpack-plugin #325". I needed to figure this out in my own project, so here it is.

copy-webpack-plugin

---

README.md

Fixes the travis and npm badges. The npm badge image link should be correct, however it didn't load at the moment because there seems to be issues with the shields.io service. At least that's what Cloudflare told me :smile:.

docs(README): fix travis & npm badges

---

webpack.config.js

According to [Webpack 2 best practices](https://webpack.js.org/guides/migrating/) rather than using the `?options` the more explicit `options` prop should be used.
(Really just a minor thing :wink:)

chore(webpack): fit to webpack v2 best practices

---

README.md

Noticed that this changes since `ng2-translate`. We need a trailing `/` in order for that to work.

docs(README): Fix asset path in example

---

src/translate.directive.ts

It made no difference in this case since Subscription is only being used as a type, and the import gets removed altogether from the generated source. But better safe than sorry.

chore(TranslateDirective): don't import all of RxJS

---

src/translate.service.ts
tests/translate.service.spec.ts

This stops multiple requests being made for the same lang file. It will now return the same observable when making duplicate requests for the same language.
Closes #397

fix(TranslateService): only make one request per lang

---

README.md
src/translate.service.ts
tests/translate.service.spec.ts

As mentioned in #330 this method would drastically simplify several of our components and allows for the idiomatic use of the `async` pipe with the `TranslationService` in the cases where using the `translate` pipe is - for some reason - undesirable. As a comparison:
Current:
```ts
@Component({ 
template: `
<div>{{a}}</div>
<div>{{b}}</div>
<div>{{c}}</div>
`
})
export class TestComponent implements OnInit, OnDestroy {
a: string;
b: string;
c: string;
private subscription: Subscription<any>;
constructor(private translate: TranslateService) { }
ngOnInit() {
this.subscription = this.translate.get(['a', 'b', 'c'])
.concat(this.translate.onLangChange.map(event => event.translations))
.subscribe(translations => {
this.a = translations.a;
this.b = translations.b;
this.c = translations.c;
});
} …
```

feat(TranslateService): streaming translations that update on language change

---

README.md
index.ts
src/translate.service.ts
tests/missing-translation-handler.spec.ts

feat(TranslateService): default language translation when current language translation is missing is now configurable.
As it is now, if KEY isn't found in current language translation, translation from default language is returned. If there isn't KEY in default language, MissingHandler is invoked. 
This PR aims to make translation to default language configurable.
In some instances we don't want default translation to mix with current translation, and we want MissingHandler to jump in instead.

feat-TranslateService: default language translation configurable

---

README.md
index.ts
src/translate.compiler.ts
src/translate.parser.ts
src/translate.service.ts
tests/translate.compiler.spec.ts
tests/translate.parser.spec.ts

This PR aims to add support for the ICU message format syntax with the help of messageformat.js. I tried to find a way of integrating this with the current ngx-translate framework in a minimally invasive way. Here's the idea:
* Extend `TranslateParser.interpolate()` to not only support string interpolation but also function interpolation: `interpolate(fn, params) => fn(params)`
* Add a new configurable `TranslateCompiler` component which allows pre-processing translation values. This is an optional step and does nothing by default.
* Add a `TranslateMessageFormatCompiler` which compiles the translation values (expected to use the ICU syntax) into interpolation functions using messageformat.js.
Corresponding issue: https://github.com/ngx-translate/core/issues/150
**Edit:** If the …

Support pluralization using messageformat.js

---

lib/src/translate.service.ts

Hi, the change fixes an issue that when the translation is in pending state, the compiler will not compile the translation and the strings on the first loaded web page are not compiled.

Fix when the pending state is true, the translation is not compiled by the compiler.

---

README.md

I wrote a simple vscode extension for ngx-translate. When you have f.e. your english translation file ```en.json``` opened then you can hit ```F1``` and type ```ngxtz: find translation zombies in this file``` and hit return. The extension will search through all .ts, .js and .html files (excluding node_modules) and show a changed version of ```en.json``` in the vscode diff editor.
I needed this for my daily work and just wrote it ... so of course at the moment it only has very basic features but it's OSS and you can contribute if you want to :)

ngx-translate-zombies vscode extension

---

lib/src/util.ts
tests/translate.service.spec.ts

shouldMerge option of the `setTranslation` method didn't handle non-valid JSON translations object such compiled translations with custom compiler.
It is now doing deep merging with lodash.
Fixes #764

fix(TranslateService): shouldMerge option now does merging with lodash

---

projects/ngx-translate/core/src/lib/translate.service.ts
projects/ngx-translate/core/tests/translate.service.spec.ts

fix(TranslateService): compile translations only once

---

README.md

Hi,
I created an extension for the VS code [Generate Translation](https://marketplace.visualstudio.com/items?itemName=thiagocordeirooo.generate-translation) to help create the translation keys without having to leave the current file.
As @ocombe suggested, I am creating this PR to add the reference of this extension in the README.
Thanks!

docs(README): add 'Generate Translation' to the Editors section (#996)

---

projects/ngx-translate/core/src/lib/translate.directive.ts
projects/ngx-translate/core/src/lib/translate.pipe.ts
projects/ngx-translate/core/src/lib/translate.service.ts
projects/ngx-translate/core/tests/translate.service.spec.ts

I went through the code base and refactored some RxJS usage where I thought it could be improved or where it was using old and deprecated notations. I'm adding comments where it's not obvious what I did there.
In general there are two larger changes:
- Replacing deprecated `subscribe(v => void, func)` calls with `subscribe({ next: v => void, error: e => void})` https://github.com/ReactiveX/rxjs/issues/4159.
- Replacing Observable checks like `typeof res.subscribe === 'function'` with `isObservable(res.subscribe)`.
All existing tests were passing I just added one more additional test for some sync behavior.

refactor: RxJS chains

---

projects/ngx-translate/core/src/lib/translate.directive.ts
projects/ngx-translate/core/tests/translate.directive.spec.ts

Issue #998: Translate directive whitespace handling can cause erroneous recursive translation

fix(directive): trim white spaces to find matching keys

---

README.md
projects/ngx-translate/core/src/lib/translate.service.ts
projects/ngx-translate/core/src/public_api.ts
projects/ngx-translate/core/tests/translate.store.spec.ts

Added an option to merge lazy loaded translations with the initially loaded ones (instead of ignoring them if already present for a given language).
Probably fixes some of the issues discussed in
https://github.com/ngx-translate/core/issues/425

feat(core): add option for lazy loaded modules to extend translations

---

README.md

Adds information about dynamically generating translation keys and piping the keys through `uppercase` and `lowercase`.

docs(README): More examples for the pipe usage

---

FIREBASE_EXAMPLE.md

Fixes a 'typo' which confused me, when I made a custom loader by following this example.

docs(firebase-example): Prefix should be in the constructor

---

projects/ngx-translate/core/src/lib/translate.service.ts

An empty string is now also allowed as default language.
It checks if the default language is null. 
The check for 'undefined' is implied because of the use of == instead of ===.

feat(service): allow empty default language string

---

projects/ngx-translate/core/src/lib/translate.parser.ts

This is a corner case, but broke the app in my case cause a number was translated

fix(service) handle non-string keys without throwing

---

projects/ngx-translate/core/src/lib/translate.service.ts

When accessing a non-existing property, JavaScript returns undefined.
The check for 'undefined' will guarantee that browserLang has been and we can safely call .indexOf()

fix(TranslateService): check whether variable contains undefined value

---

projects/ngx-translate/core/src/lib/translate.pipe.ts
projects/ngx-translate/core/tests/translate.pipe.spec.ts

Forgive me I didn't see a contributing guideline and I wasn't sure if I sure file a bug for this/wanted to start more of a discussion about how TranslatePipe should handle non-string input.
I write shared components for other teams to use (think asset kit), and don't have strict control over inputs. We can put in arg validation as needed but I did run into a case that IMO the TranslatePipe should handle on its own.
TranslatePipe throws a `Parameter "key" required` error for `number` type input. IMO this could just return back the number that was passed in, curious on others' opinions?
We have a shared filtering/searching component that displays a list of filter labels the user can select from such as:
The basic replication code boils down to:
```html
<span>{{ 2018 | translate }}</span> …
```

fix(TranslatePipe): handle non string input

---

projects/ngx-translate/core/src/lib/translate.directive.ts

This pull request is proposal to fix the following issue
https://github.com/ngx-translate/core/issues/1164
This produce the same behavior as in v11.0.1, the directive use the current text/value computed by angular change detection when the keys has neither an entry in the translation file for this language, nor in the default language translation file

fix(directive): untranslated keys return the last cumputed value

---

projects/ngx-translate/core/src/lib/translate.directive.ts
projects/ngx-translate/core/tests/translate.directive.spec.ts

The problem with issue #998 is, that at some node.originalContent in translate.directive.ts is overwritten by a translation that was assigned previously. So the translation key gets destroyed and no further translations could be made.
The bugfix introduces a new variable (node.lookupKey) that is generated once (by this.key or the trimmed content of the node) and used in further translations instead of calculating it over and over again. 
Since I changed no existing tests, I assume that alle existing functionality still works. I added new test to verify that the problem with white spaces are fixed.

fix(directive): avoid recursive errors when using keys with whitespaces

---

README.md
projects/ngx-translate/core/src/lib/translate.service.ts
projects/ngx-translate/core/src/public_api.ts

- Default language option added for specifying the language at the time of defining the configuration in `forRoot` or `forChild` method. 
- Now user don't need to explicitly calls the `setRootLanguage` method for defining the default language at the initial time.
- Code formatted.
- Example added for `defaultLanguage`.

feat(service): add option to set default language in root config

---

README.md

The relative URL redirected to a subdirectory of README file's location, and it was wrong. I replaced it with an absolute URL

README.md: correct link to changelog

---

projects/ngx-translate/src/lib/util.ts

This pull request addresses a bug in the `isDict` method that previously did not explicitly check for null values. The original implementation of the `isDict` method only checked if the value was an object and not an array. 
This behavior is causing some translation values with null values to be converted into an empty object. 
**Changes made:**
1. Added a null check to the `isDict` method to ensure that null values are not incorrectly identified as dictionaries.

Fix: Check for null values in isDict method

---

projects/ngx-translate/src/lib/translate.service.spec.ts
projects/ngx-translate/src/lib/translate.service.ts
projects/ngx-translate/src/lib/util.ts

- **utils**: add function type inference
- **runInterpolation**: avoid null/undefined & refactor
- **InterpolatableTranslation**: remove any in favour of undefined & null
- Makes the required test changes
I've tested it on my project and it seems to work, I'm not just I get all the different possibilities.  
Therefore I preferred to do a small PR, but maybe we could use a small `-rc` release with some testers
What about we create a more robust example inside the `test-app` folder, where we could really test out everything ?

refactor(utils): type inference

---

projects/ngx-translate/src/lib/translate.service.ts

After analyse and debugg code we encounter that even we provide no params the logic runs through the interpolation stack.
If their no Params provide an exit is here already possible to return the translated value directly

Add fast exit if no params provided

---

projects/ngx-translate/src/lib/translate.parser.spec.ts
projects/ngx-translate/src/lib/translate.pipe.ts
projects/ngx-translate/src/lib/translate.service.spec.ts
projects/ngx-translate/src/lib/translate.service.ts

**Changes**
* `TranslatePipe` now explicitly accepts `null` and `undefined` and returns `Translation`. The code already guards against falsy values and specifying it explicitly helps when used with `strictNullChecks` in `tsconfig`. Otherwise, you may get a bunch of errors when an optional or nullable field is passed to the pipe.
* Replaced `any` with `unknown` in `InterpolationParams`.
* Fixes a test on non-English machines.

Improve type safety of TranslateService and TranslatePipe

---

README.md

Set it to the maintained fork.
See https://github.com/biesbjerg/ngx-translate-extract/issues/246#issuecomment-1353101571 for details.

Update the link to `ngx-translate-extract` in README
