- src/translate.parser.ts
- src/translate.pipe.ts
- src/translate.service.ts
Fix: Remove tslint errors on build (semicolons, qoutes type, declaration order)
> Add: Show key instead "" when no value in translate files

- package.json
- src/translate.pipe.ts
- src/translate.service.ts
> chore(package): update angular to alpha 53

- README.md
- ng2-translate.ts
- package.json
- src/missingtranslationhandler.interface.ts
- src/translate.service.ts
- tests/translate.service.spec.ts
solves #23 
Tests & Readme are added.
Update:
I tried update zone.js version to 0.5.11 that the peer dependency is automtically satisfied. In this case the build will fail because tsd isn't installed. tsd is now deprecated.
Angular2 beta-3 needs zone.js 0.5.11 so you could maybe update it.
> Missing Translation Handler

- README.md
- bundles/ng2-translate.js
- karma.conf.js
- ng2-translate.ts
- src/translate.parser.ts
- src/translate.service.ts
- tests/translate.parser.spec.ts
- tests/translate.pipe.spec.ts
- tests/translate.service.spec.ts
- tsconfig.json
Finally this PR has not much to do with #48, since Angular DI supports classes  and not interfaces.
Note! There are breaking changes in this PR.
> configure of TranslateLoader and MissingTranslationHandler with angular2 DI only (#48)

- src/translate.service.ts
Introduce LangChangeEvent interface
> Introduce LangChangeEvent interface

- README.md
This adds a Table of Contents for convenience and an 'Additional Framework Support' section since this library is now officially supported with `nativescript-angular` :+1: 
It could seemingly be bridged to work with other `native` or non-`native` frameworks so figured having a section would provide room to grow :)
> feat(readme): added TOC and additional framework support section

- bundles/ng2-translate.js
- package.json
- src/translate.pipe.ts
- tests/translate.pipe.spec.ts
- tests/translate.service.spec.ts
Angular 2.0.0-beta.16 compatibility issue fixed.
> fix(npm): Updated to beta 16

- bundles/ng2-translate.js
- src/translate.parser.ts
- tests/translate.parser.spec.ts
Parser should interpolate with falsy values like empty strings and zero.
> fix(Parser): accept falsy values

- README.md
- Update Readme to remove [deprecated](https://github.com/angular/angular/commit/a6ad61d83e2c423bd36cdda145fd29f72974535c) Provide()  calls
> Remove deprecated provide() calls

- src/translate.service.ts
Removed the unused ```Http``` dependency.
> #146 - Remove Http dependency from the TranslateService class

- README.md
Add code snippet to use in case of AoT compiling (especially on Ionic 2 from RC 0)
See #218
> Update README to explain how to deal with AoT

- README.md
A forgets from me in the previous PR
> Update README.md about the new method

- README.md
- src/translate.service.ts
- tests/translate.service.spec.ts
> Added support for Language Culture Name

- README.md
Feel free to improve upon anything I changed. It are just suggestions, it's your project so I will adhere to anything you want, as long as the information is correct :).
> update the docs

- package.json
ERROR [coverage]: TypeError: remap is not a function
at onCoverageComplete (\node_modules\karma-remap-coverage\remap-coverage.js:23:23)
> Resolve karma test

- src/translate.service.ts
Emit all translations instead of newly added translations
> Emit all translations - fixes #367

- README.md
@biesbjerg/ngx-translate-po-http-loader
> Update README.md for @biesbjerg/ngx-translate-po-http-loader

- src/translate.service.ts
- src/util.ts
@ocombe AFAIK you haven't updated the NPM package yet, well... the deepMerge repo was not working as expected XD so i created a new function that is working (at least for me)
> Fix and simplify deep merging

- MIGRATION_GUIDE.md
Fix a small typo inside MIGRATION_GUIDE.md
> Fix typo in MIGRATION_GUIDE.md

- FIREBASE_EXAMPLE.md
- README.md
Added FIREBASE_EXAMPLE.MD and added link from README.md (in custom loader section).
> Updated docs with Firebase custom loader example

- README.md
updated the TranslateHttpLoader example to use HttpClient and HttpClientModule
> updated Http to HttpClient in TranslateHttpLoader example

- examples/ionic/.gitignore
- examples/ionic/config.xml
- examples/ionic/ionic.config.json
- examples/ionic/package-lock.json
- examples/ionic/package.json
- examples/ionic/src/app/app.component.ts
- examples/ionic/src/app/app.module.ts
- examples/ionic/src/index.html
- examples/ionic/src/pages/about/about.ts
- examples/ionic/src/pages/contact/contact.ts
- examples/ionic/src/pages/home/home.ts
- examples/ionic/src/pages/tabs/tabs.ts
I updated the Ionic example to our latest release and enabled lazy loaded pages by default.
> docs(): update Ionic example

- README.md
The information is missing on README.md. It's worth to be added.
> Describe the latest compatible version with Angular 4

- README.md
change the forRoot link as the old one is no longer working.
> update forRoot doc link

- README.md
docs(README): reference ngx-translate-module-loader
> docs(README): reference ngx-translate-module-loader

- README.md
The old link doesn't work anymore. So I've updated it.
> docs(README): update shared modules link

- README.md
DOCS(readme): added ngx-translate-lint
> docs(readme): add ngx-translate-lint

- README.md
Simple and useful pipe for cutting translations ✂️
> docs(readme): add ngx-translate-cut plugin

- README.md
I added a section in the FAQ to explain how to apply hot reloading of translations in an application. Thanks to the explanation of @keradus in #874
> docs(readme): add section on hot reloading of translations

- projects/ngx-translate/core/src/lib/translate.service.ts
- projects/ngx-translate/core/tests/translate.service.spec.ts
> fix(service): make initial translation streaming lazy

- projects/ngx-translate/core/src/public_api.ts
According to https://angular.io/api/core/ModuleWithProviders you should add a generic type to any ModuleWithProviders
> fix(module): add `TranslateModule` type to `ModuleWithProviders`

- README.md
Added a free translations editor, got permission through Twitter
> chore(README): add crowdl.io to the list of editors

- README.md
Adding "lingua" to list of visual studio code extensions.
Got permission via Twitter
> chore(README): add vscode lingua to extension section

- README.md
Hi, may I allow myself to advertise for the loader I just made?
> docs(README): add new community loader for browser extensions

- projects/ngx-translate/package.json
Add urls to link the repo with the npm page
> docs(package.json): urls

- eslint.config.js
- projects/ngx-translate/eslint.config.js
- projects/test-app/src/app/app.component.ts
- **eslint.config.ts** - Prefix: from `lib` to `app`
- **app.component.ts** : remove unused & correctly order imports
> refactor(esLint): prefix

- .gitignore
- .husky/commit-msg
- commitlint.config.ts
- package-lock.json
- package.json
Enable pre-commit hooks with the help of [Husky](https://github.com/typicode/husky)
Actually, only added a control over the commit message, to enable future automatic version update & changelogs
- [CommitLint](https://commitlint.js.org/) 
- [CommitLint conventional config](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional)
Also disabled `.vsCode` change detection
> ci: husky & commitLint

- .husky/pre-commit
- package-lock.json
- package.json
Ensure prettier is ran against the staged code and this code uniquely
> ci(husky): lint-staged
